name: dotnet-ci

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: |
          dotnet restore ./src/FitnessTracker.Api/FitnessTracker.Api.csproj
          dotnet restore ./tests/FitnessTracker.Tests/FitnessTracker.Tests.csproj
      - name: Build
        run: |
          dotnet build ./src/FitnessTracker.Api/FitnessTracker.Api.csproj --no-restore --configuration Release
          dotnet build ./tests/FitnessTracker.Tests/FitnessTracker.Tests.csproj --no-restore --configuration Release
      - name: Test
        run: dotnet test ./tests/FitnessTracker.Tests/FitnessTracker.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"
